version: "3.9"
name: blue_green_demo

services:
  postgres:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./services/postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: ${POSTGRES_USER-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-password}
      POSTGRES_DB: ${POSTGRES_DB-my_postgres}
    ports:
      - 5433:5432
    networks:
      - default

volumes:
  pgdata:
    driver: local

networks:
  default:
    driver: bridge
