---
dbt_blue_green_demo:
  outputs:
    blue:
      type: postgres
      threads: 1
      host: 0.0.0.0
      port: 5433
      user: postgres
      pass: password
      dbname: my_postgres
      schema: dbt_prod_blue

    green:
      type: postgres
      threads: 1
      host: 0.0.0.0
      port: 5433
      user: postgres
      password: password
      schema: dbt_prod_green
      dbname: my_postgres

  target: blue
